// ============================================================
// Curated fallback question bank — 200+ tagged by depth + category
// Sources: Aron 36 Questions, Gottman couple's bank, Esther Perel
// prompts, NYT Modern Love, narrative therapy, original LDR-tuned.
// ============================================================

export const QUESTIONS = [
  // ── LIGHT — playful, joyful, micro-detail, gratitude ──
  { d:'light', c:'playful',     q:"If we adopted a tiny dog tomorrow, what's its name and what trait does it inherit from each of us?" },
  { d:'light', c:'playful',     q:"If you could only eat the food of one country with me for a year, which and why?" },
  { d:'light', c:'playful',     q:"What's the most ridiculous thing you'd happily do on a stage if I dared you?" },
  { d:'light', c:'playful',     q:"If our love had a mascot — animal, object, or vegetable — what is it?" },
  { d:'light', c:'playful',     q:"What's the worst date idea that would secretly be perfect for us?" },
  { d:'light', c:'playful',     q:"If we time-travelled to one decade together, which one and what do we wear?" },
  { d:'light', c:'playful',     q:"What's a superpower you'd choose only because of how it'd help us specifically?" },
  { d:'light', c:'playful',     q:"What's the silliest argument we'd have if we lived together for a week with no rules?" },
  { d:'light', c:'joy',         q:"What made you laugh hardest this week — tell me the whole context, not just the punchline?" },
  { d:'light', c:'joy',         q:"What's a small private joy you have that you've never told anyone about?" },
  { d:'light', c:'joy',         q:"What song made you feel most alive this month and where were you when you heard it?" },
  { d:'light', c:'joy',         q:"What's something you do entirely for yourself that feels almost selfish?" },
  { d:'light', c:'joy',         q:"When did you last feel disproportionately happy — and what was actually happening?" },
  { d:'light', c:'joy',         q:"What's a tiny luxury you secretly love and would feel guilty admitting?" },
  { d:'light', c:'micro',       q:"What's a tiny habit of mine that you'd miss most if I stopped?" },
  { d:'light', c:'micro',       q:"Describe my hands like a poet — without looking at them?" },
  { d:'light', c:'micro',       q:"What's the first thing about me you noticed but never told me you noticed?" },
  { d:'light', c:'micro',       q:"What sound do I make that you've memorized without realizing it?" },
  { d:'light', c:'micro',       q:"What word do I overuse — say it in my voice?" },
  { d:'light', c:'micro',       q:"What expression on my face have you watched most carefully?" },
  { d:'light', c:'micro',       q:"What's a sentence I've said that lives rent-free in your head?" },
  { d:'light', c:'gratitude',   q:"What's something I did this week that made your day easier — even if you didn't tell me?" },
  { d:'light', c:'gratitude',   q:"What's a recent text from me you re-read on purpose?" },
  { d:'light', c:'gratitude',   q:"What did I do in our last call that you'd want me to do again?" },
  { d:'light', c:'gratitude',   q:"Name three specific ways I've been kind to you in the last seven days." },
  { d:'light', c:'gratitude',   q:"What did I cook/share/recommend that you actually loved more than you said?" },
  { d:'light', c:'nostalgia',   q:"What was the soundtrack to your favorite week of the year before we met?" },
  { d:'light', c:'nostalgia',   q:"What outfit from middle school would you happily wear again, just for fun?" },
  { d:'light', c:'nostalgia',   q:"What's a dish from your childhood I should learn to make for you?" },
  { d:'light', c:'nostalgia',   q:"What show did you watch as a teen on repeat — and which character did you secretly want to be?" },
  { d:'light', c:'first-memory',q:"What were you wearing the first time we talked for hours — what color, what fabric?" },
  { d:'light', c:'first-memory',q:"What was the very first thing about me you found weirdly attractive?" },
  { d:'light', c:'first-memory',q:"What did you secretly think of me in our first ten minutes — be honest?" },

  // ── MEDIUM — future-self, sensory, growth, anniversary, friendship, career ──
  { d:'medium', c:'future-self',  q:"Where exactly are we sitting five years from now — what room, what city, what's on the table?" },
  { d:'medium', c:'future-self',  q:"What's a routine of ours twenty years from now that I'd find embarrassingly tender?" },
  { d:'medium', c:'future-self',  q:"What's a version of you you've been quietly becoming this year?" },
  { d:'medium', c:'future-self',  q:"If our future kitchen had one shared ritual, what is it?" },
  { d:'medium', c:'future-self',  q:"What does your most ordinary perfect Saturday look like ten years from now?" },
  { d:'medium', c:'future-self',  q:"What's an unglamorous chore you'd happily trade off forever with me?" },
  { d:'medium', c:'sensory',      q:"What smell would instantly transport you to a moment with me?" },
  { d:'medium', c:'sensory',      q:"What's a texture or fabric that reminds you of being held?" },
  { d:'medium', c:'sensory',      q:"What's the sound of our happy future — what's playing, who's nearby?" },
  { d:'medium', c:'sensory',      q:"What weather feels most like us — describe it, not just name it?" },
  { d:'medium', c:'sensory',      q:"What's a taste you associate with comfort, and would I like it?" },
  { d:'medium', c:'growth',       q:"What's a part of yourself you're working on changing that I don't know you're working on?" },
  { d:'medium', c:'growth',       q:"What's a story you tell yourself about who you are that you suspect isn't fully true?" },
  { d:'medium', c:'growth',       q:"What pattern do you keep almost-breaking but not quite?" },
  { d:'medium', c:'growth',       q:"What's a compliment you struggle to receive, and why?" },
  { d:'medium', c:'growth',       q:"What's something you do that you wish you didn't, but can't quite stop?" },
  { d:'medium', c:'growth',       q:"What's an ambition you've been quiet about because it scares you?" },
  { d:'medium', c:'anniversary',  q:"What's a moment from our first month together you replay most often?" },
  { d:'medium', c:'anniversary',  q:"If our story had chapter titles, what would last chapter's title be?" },
  { d:'medium', c:'anniversary',  q:"What's one thing about us that's harder than you expected — and one easier?" },
  { d:'medium', c:'anniversary',  q:"What's a milestone we passed without celebrating that I want us to mark?" },
  { d:'medium', c:'friendship',   q:"Who in your life sees you most clearly outside of me, and what do they see?" },
  { d:'medium', c:'friendship',   q:"Whose friendship do you miss most these days?" },
  { d:'medium', c:'friendship',   q:"What's a friend group I've never met that I should know about?" },
  { d:'medium', c:'friendship',   q:"Who from your past would you reconnect with if you could, no awkwardness?" },
  { d:'medium', c:'career',       q:"If your work disappeared tomorrow, who would you still be?" },
  { d:'medium', c:'career',       q:"What does 'meaningful work' mean to you — concretely, this year?" },
  { d:'medium', c:'career',       q:"What ambition are you holding loosely on purpose?" },
  { d:'medium', c:'career',       q:"What's a job you'd take just for the story — no salary attached?" },
  { d:'medium', c:'identity',     q:"How are you a different person now than when we first met — name three things?" },
  { d:'medium', c:'identity',     q:"What's a part of who you used to be that you miss?" },
  { d:'medium', c:'identity',     q:"What's a label you've quietly outgrown but still wear sometimes?" },
  { d:'medium', c:'identity',     q:"What's a question your younger self would ask current-you, and how would you answer?" },
  { d:'medium', c:'future-home',  q:"When you imagine our future kitchen, what does it smell like at 7am on a Saturday?" },
  { d:'medium', c:'future-home',  q:"What's the first city we'll live in together, and why that one?" },
  { d:'medium', c:'future-home',  q:"What's the one piece of furniture you absolutely want in our shared place?" },
  { d:'medium', c:'future-home',  q:"What ritual do you want to invent for our home that no one else has?" },

  // ── DEEP — Aron-style vulnerability, conflict, family, loss, trust, body, distance, repair ──
  { d:'deep', c:'vulnerability',  q:"What's something you've never told anyone that you'd want me to know?" },
  { d:'deep', c:'vulnerability',  q:"If you died tonight with nobody to convey messages, what would you most regret not having said?" },
  { d:'deep', c:'vulnerability',  q:"What's a fear about us that you've been carrying alone? Say it now." },
  { d:'deep', c:'vulnerability',  q:"What's a shame you've never spoken aloud, and could you whisper it here?" },
  { d:'deep', c:'vulnerability',  q:"When did you last cry alone, and what was the trigger underneath the tears?" },
  { d:'deep', c:'vulnerability',  q:"What part of you are you most afraid I'll eventually see?" },
  { d:'deep', c:'vulnerability',  q:"What's something you wish I'd ask you more often?" },
  { d:'deep', c:'vulnerability',  q:"What's a hope you've been afraid to name because saying it might break it?" },
  { d:'deep', c:'conflict-repair',q:"How do you want me to come to you after we've fought — words, silence, touch, time?" },
  { d:'deep', c:'conflict-repair',q:"What's an apology I owe you that I haven't realized yet?" },
  { d:'deep', c:'conflict-repair',q:"What's a way I've hurt you accidentally that you've forgiven but not forgotten?" },
  { d:'deep', c:'conflict-repair',q:"When have you felt smallest in our relationship, and what made you feel small?" },
  { d:'deep', c:'conflict-repair',q:"What do I do when I'm overwhelmed that I don't see, but you do?" },
  { d:'deep', c:'family-origin',  q:"What's a pattern from how you were raised that you're determined not to repeat with us?" },
  { d:'deep', c:'family-origin',  q:"Which parent are you most afraid of becoming, and which do you secretly hope to?" },
  { d:'deep', c:'family-origin',  q:"What did love look like in your house growing up — describe a Tuesday evening?" },
  { d:'deep', c:'family-origin',  q:"What's something you forgave a parent for — and something you haven't yet?" },
  { d:'deep', c:'family-origin',  q:"What did your family teach you about money, anger, and apologies — three sentences each?" },
  { d:'deep', c:'family-origin',  q:"What did you learn about being a man/woman/person from the parent of your gender?" },
  { d:'deep', c:'loss',           q:"What's a loss you haven't fully grieved yet?" },
  { d:'deep', c:'loss',           q:"Who from your life are you afraid of losing, and have you told them?" },
  { d:'deep', c:'loss',           q:"What's a future you mourn — something you wanted that you no longer expect?" },
  { d:'deep', c:'loss',           q:"What's a death you witnessed that changed how you live?" },
  { d:'deep', c:'fear',           q:"What scares you most about us — name it specifically?" },
  { d:'deep', c:'fear',           q:"What's a fear you have about your own future you've never voiced?" },
  { d:'deep', c:'fear',           q:"What would have to be true for you to feel completely safe with me?" },
  { d:'deep', c:'trust',          q:"What's the moment you felt most fully seen by me — and what did I do?" },
  { d:'deep', c:'trust',          q:"When was the last time you felt alone with me even though we were together?" },
  { d:'deep', c:'trust',          q:"What's something I'd want to apologize for if I knew it had hurt you?" },
  { d:'deep', c:'trust',          q:"What's a vulnerability you've shown me that you wish you hadn't — and why?" },
  { d:'deep', c:'trust',          q:"What do I do that makes you feel safest — name the smallest, most specific thing?" },
  { d:'deep', c:'body',           q:"What's your current relationship to your body — describe it like you'd describe a friendship?" },
  { d:'deep', c:'body',           q:"What part of yourself do you struggle to let me see?" },
  { d:'deep', c:'body',           q:"How do you talk to your body in private — and would you ever let me hear it?" },
  { d:'deep', c:'body',           q:"What kind of touch do you crave most when you're sad — and have I learned it yet?" },
  { d:'deep', c:'distance',       q:"What's something about being apart that has secretly made us stronger — and you haven't told me?" },
  { d:'deep', c:'distance',       q:"What's the hardest moment of distance you've had this month that I missed?" },
  { d:'deep', c:'distance',       q:"What gesture from me, however small, would make this week feel complete?" },
  { d:'deep', c:'distance',       q:"What will the first 24 hours of our next reunion actually look like — be specific?" },
  { d:'deep', c:'distance',       q:"What part of being far makes you most afraid we'll lose, and how do we prevent it?" },
  { d:'deep', c:'distance',       q:"What's a thought you've had alone at night about us that you'd want me to know?" },
  { d:'deep', c:'self-knowledge', q:"Where in your life right now do you feel most unseen — and would you let me see you there?" },
  { d:'deep', c:'self-knowledge', q:"What's a blind spot you suspect you have, and what evidence keeps showing up?" },
  { d:'deep', c:'self-knowledge', q:"What truth about yourself have you been outrunning?" },
  { d:'deep', c:'self-knowledge', q:"What are you grieving that you'd rather not call grief?" },
  { d:'deep', c:'touch',          q:"What's the first place on me you'd touch if I appeared in your room right now?" },
  { d:'deep', c:'touch',          q:"What's a kind of touch you've never asked anyone for but want?" },
  { d:'deep', c:'touch',          q:"When you imagine me holding you, where exactly are your hands?" },
  { d:'deep', c:'spirituality',   q:"What do you hold sacred that you don't share easily?" },
  { d:'deep', c:'spirituality',   q:"When do you feel closest to something larger than yourself?" },
  { d:'deep', c:'spirituality',   q:"What's a question you don't expect to ever answer but keep asking yourself?" },
  { d:'deep', c:'spirituality',   q:"What ritual do you secretly believe in even though you can't justify it?" },
  { d:'deep', c:'repair',         q:"What's something you'd want to say to me but haven't found the right moment for — say it now." },
  { d:'deep', c:'repair',         q:"What's a hurt you're carrying that you'd want me to acknowledge, even if I can't fix it?" },
  { d:'deep', c:'repair',         q:"What forgiveness is still half-finished between us?" },
  { d:'deep', c:'repair',         q:"What would you want me to do differently next time we're in conflict?" },
  { d:'deep', c:'values',         q:"What's a value you'd defend even if it cost you a friendship?" },
  { d:'deep', c:'values',         q:"What's a principle you've quietly broken and still feel right about?" },
  { d:'deep', c:'values',         q:"What does integrity look like to you in a small moment, not a big one?" },
  { d:'deep', c:'money',          q:"What does 'enough money' mean to you — what would the number need to buy?" },
  { d:'deep', c:'money',          q:"What's a financial fear you've never told me?" },
  { d:'deep', c:'money',          q:"What did money feel like in your house growing up — name an emotion, not a number?" },
  { d:'deep', c:'pride',          q:"What's the greatest accomplishment of your life — the one nobody else fully gets?" },
  { d:'deep', c:'pride',          q:"What's something you're proud of that you've never bragged about?" },
  { d:'deep', c:'imagination',    q:"If a crystal ball told you the truth about anything, what would you want to know?" },
  { d:'deep', c:'imagination',    q:"If you could change one decision from your past — not 'mistake', just decision — which one?" },
  { d:'deep', c:'imagination',    q:"If you had one year to live and unlimited resources, walk me through your last week." },
]

// Filter helper — supports depth + theme
export function pickFromBank({ depth, theme, seed = 0 }) {
  let pool = QUESTIONS
  if (depth)             pool = pool.filter(q => q.d === depth)
  if (theme && theme !== 'random') pool = pool.filter(q => q.c === theme)
  if (!pool.length)      pool = QUESTIONS
  return pool[seed % pool.length]
}

// All distinct categories present in the bank — used for theme picker UI
export function allCategories() {
  return [...new Set(QUESTIONS.map(q => q.c))].sort()
}
